### PR TITLE
Fix React 15.3 warning.

### PR DESCRIPTION
**Pull request by farrrr**
upgrade react-bootstrap version to v0.30.2.
https://facebook.github.io/react/warnings/dont-call-proptypes.html

### CODE REVIEW

**Comment by avesus** [comment]
@DropsOfSerenity please merge this PR, people are suffering :-)

**Comment by DropsOfSerenity** [comment]
Ok I will check this PR tonight to make sure nothing breaks.

**Comment by ames89** [comment]
how is the check going? is it factible?

**Comment by DropsOfSerenity** [comment]
Thank you for the pull request, and sorry for the delay. Lots of work lately :) I'll get a release pushed out for this.

**Pull request merged**
